@ProductAnalyzer.WebApi_HostAddress = http://localhost:5136

GET {{ProductAnalyzer.WebApi_HostAddress}}/product/
Accept: application/json

###

GET {{ProductAnalyzer.WebApi_HostAddress}}/product/MostExpensiveAndCheapest/
Accept: application/json

###

GET {{ProductAnalyzer.WebApi_HostAddress}}/product/MatchingPrice?price=1.50
Accept: application/json

###
